### ISSUE TITLE
Achievements page

### ISSUE THREAD

**Issue by zam264** [zam264/CommonSquirrel#17]
Create an achievements scene with different height achievements based on each play through

Placed in the options screen temporarily

**Comment by zam264** [comment]
We would like to have thumbnail images for each achievement as well as a witty title.

We can add the titles to the excel sheet.

**Comment by zam264** [comment]
I've created a few test goals for achievements, nothing related to our goals thus far.

Achievements should update as soon as you achieve a new goal.

Some sort of notification when a new achievement is unlocked would be good.

I will begin entering all of our goals, distances, names and eventually images as we come up with them. (use the spread sheet that @zgp1001 created)

**Comment by zam264** [comment]
We need to begin to create achievement badges for each achievement

**Comment by zgp1001** [comment]
For the images we are going to take Public Domain images from Wikipedia - preferable ones that don't require credits given to the uploader. 

I think we are going with 256x256 for the size of the images. Jpg or png format should be fine. 

These images should then be processed in PS/GIMP using "Filter->Artistic->Cartoon". If the image still isn't toony enough play around with other filters. 

I assigned us each images to create on the excel sheet of achievements. We should also probably create a folder in the imgs folder for the achievements images so that the folder doesn't get too crowded.

**Comment by WBotzer** [comment]
Need to make border around achievements to improve the looks

**Comment by WBotzer** [comment]
Borders added in
